import { Routes } from '@angular/router';
import { TrangchuComponent } from './trangchu/trangchu.component';
import { SanphamComponent } from './sanpham/sanpham.component';
import { ChiTietSanPhamComponent } from './chitietsanpham/chitietsanpham.component';
import { GiohangComponent } from './giohang/giohang.component';
import { DangkyComponent } from './dangky/dangky.component';
import { DangnhapComponent } from './dangnhap/dangnhap.component';
import { UserInfoComponent } from './userinfo/userinfo.component';
import { CheckoutComponent } from './checkout/checkout.component';
import { DonhangComponent } from './donhang/donhang.component';
import { lichsudonhangComponent } from './lichsudonhang/lichsudonhang.component';
import { ForgotPasswordComponent } from './forgot-password/forgot-password.component';
import { VerifyOtpComponent } from './verify-otp/verify-otp.component';
import { ResetPasswordComponent } from './reset-password/reset-password.component';
import { TintucComponent } from './tintuc/tintuc.component';
import { NewsDetailComponent } from './news-detail/news-detail.component';
import { WishlistComponent } from './wishlist/wishlist.component';
import { PaymentComponent } from './components/payment/payment.component';
import { PaymentResultComponent } from './components/payment-result/payment-result.component';
import { InvoiceComponent } from './components/invoice/invoice.component';

export const routes: Routes = [
  { path: '', component: TrangchuComponent },
  { path: 'trangchu', component: TrangchuComponent },
  { path: 'sanpham', component: SanphamComponent },
  { path: 'chitiet/:id', component: ChiTietSanPhamComponent },
  { path: 'chitietsanpham/:id', component: ChiTietSanPhamComponent },
  { path: 'product/:id', component: ChiTietSanPhamComponent },
  { path: 'giohang', component: GiohangComponent },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'verify-otp', component: VerifyOtpComponent },
  { path: 'reset-password', component: ResetPasswordComponent },
  { path: 'dangky', component: DangkyComponent },
  { path: 'dangnhap', component: DangnhapComponent },
  { path: 'userinfo', component: UserInfoComponent },
  { path: 'checkout', component: CheckoutComponent },
  { path: 'donhang', component: DonhangComponent },
  { path: 'lichsudonhang', component: lichsudonhangComponent },
  { path: 'news', component: TintucComponent },
  { path: 'news/:id', component: NewsDetailComponent },
  { path: 'wishlist', component: WishlistComponent },
  { path: 'payment', component: PaymentComponent },
  { path: 'payment-result', component: PaymentResultComponent },
  { path: 'invoice', component: InvoiceComponent },
];
